# Generated by Django 4.2.4 on 2023-08-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('role', models.TextField(max_length=200)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=300)),
                ('salary', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('description', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
