# Generated by Django 4.2.3 on 2023-08-13 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 13, 9, 8, 16, 460426, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
