# Generated by Django 4.2.3 on 2023-08-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_budget_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 19, 15, 29, 45, 873787, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
