# Generated by Django 4.2.3 on 2023-08-22 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_register_alter_expense_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 22, 22, 35, 0, 632431, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
