# Generated by Django 4.2.3 on 2023-08-23 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_expense_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.DateField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('category', models.TextField(max_length=100)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 23, 15, 2, 23, 349635, tzinfo=datetime.timezone.utc), max_length=100),
        ),
    ]
