# Generated by Django 4.2.3 on 2023-08-30 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_expense_day_alter_sales_date_alter_sales_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='pay_method',
            field=models.TextField(default='cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 30, 0, 8, 16, 501949, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 30, 0, 8, 16, 504941, tzinfo=datetime.timezone.utc), max_length=80),
        ),
    ]
