# Generated by Django 4.2.3 on 2023-08-31 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_expense_day_alter_sales_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 31, 15, 45, 56, 500305, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 8, 31, 15, 45, 56, 501303, tzinfo=datetime.timezone.utc), max_length=80),
        ),
        migrations.AlterField(
            model_name='sales',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
