# Generated by Django 4.2.3 on 2023-09-01 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_expense_day_alter_sales_day_alter_slides_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 9, 1, 10, 55, 44, 133476, tzinfo=datetime.timezone.utc), max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='day',
            field=models.CharField(default=datetime.datetime(2023, 9, 1, 10, 55, 44, 133476, tzinfo=datetime.timezone.utc), max_length=80),
        ),
    ]
